### ISSUE TITLE
mapmap(...).geometry is not a function

### ISSUE THREAD

**Issue by maptastik** [floledermann/mapmap.js#1]
Seems like a really neat library! Little issue. When I use the version of mapmap.js from the mapmap.js repo to create your simplest map example, I get an error `mapmap(...).geometry is not a function`. However, when I use the version from mapmap-examples repo, the map draws as expected. The biggest difference I see is **mapmap-examples/mapmap.js** contains your **datadata.js** library whereas **mapmap.js/mapmap.js** does not. Not sure if it's an issue on my end, but thought I'd let you know!

**Comment by floledermann** [comment]
Oops, browserify was not behaving as inteded... fixed in 0.2.2.
