### ISSUE TITLE
Improve labeling of highest category for threshold scale

### ISSUE THREAD

**Issue by wahlatlas** [floledermann/mapmap.js#11]
suppose you are using a threshold scale for 5 colors like this

```
       scale: 'threshold',
       domain: [400, 500, 600, 700],
```

then the upper most category should be labeld either 
**> 700** 
or 
**700 and above** 
but not both

see here 
![legendlabels](https://cloud.githubusercontent.com/assets/4449821/9172768/090e7928-3f76-11e5-982b-e77598e51c44.png)

**Comment by floledermann** [comment]
This should have been fixed by the recent refactoring of legend generation. Built mapmap.js checked in in master, release forthcoming.

Also watch out for examples collection detailing legend configuration coming soon.
