### ISSUE TITLE
Request: Allow different/arbitrary delimiters in csv files

### ISSUE THREAD

**Issue by wahlatlas** [floledermann/mapmap.js#15]
Especially in the 'de' localization, csv files often come with semicolon as delimiters (e.g. default in MS Office). This is of very low priority of course as it is easily modifiable.

**Comment by floledermann** [comment]
You can do this by either registering a file handler for a given extension with the datadata instance contained in mapmap:

``` js
var dd = mapmap.datadata;
dd.registerFileHandler('csv', dd.rowFileHandler(d3.dsv(';','text/plain')));
//...
```

or, for one-shot customization, by passing the `fileHandler` option to `.data()`:

``` js
var dd = mapmap.datadata;
//...
map.data('places.csv', { map: 'code', fileHandler: dd.rowFileHandler(d3.dsv(';','text/plain'))
```

Note that this will only affect the row parsing, not the parsing of individual fields - e.g. if your files uses commas as decimal point, you need to take care of this separately (e.g. through the `accessor` option).

The file handler mechanism had been in place before, but is now exposed publicly in the master branch build.
