### ISSUE TITLE
IE11 throws script error "Promise is undefined" (nothing gets displayed)

### ISSUE THREAD

**Issue by wahlatlas** [floledermann/mapmap.js#16]
In Internet Explorer Version 9 & 11 (tested on Windows 7) I'll get nothing else than a script error in the console "Promise is undefined" which points to parts of mapmap.js that are marked deprecated. However I couldn't get rid of those parts.

You may check with this example that is now working as expected in other browser as of v0.26
http://vis.uell.net/mapmap/test_026.html

**Comment by floledermann** [comment]
In IE and older versions of other browsers you need to load a Polyfill for the Promise object, which is built-in in newer JS engines. It is sufficient to load the corresponding JS file before mapmap.js, e.g. from here: https://raw.githubusercontent.com/floledermann/mapmap-examples/master/lib/promise-1.0.0.js

I am considering to integrate the polyfill in future versions (#17), however I haven' t found a good strategy to do so yet.

**Comment by floledermann** [comment]
Updated readme to clarify the need for the polyfill.

**Comment by wahlatlas** [comment]
Thanks, that does the trick
http://vis.uell.net/mapmap/test_026promise.html
