### ISSUE TITLE
behavior.zoom does not work without hoverInfo

### ISSUE THREAD

**Issue by wahlatlas** [floledermann/mapmap.js#18]
It looks to me as if the zoom behavior can only be successfully applied when .hoverInfo is also present.
See http://vis.uell.net/mapmap/test_026.html as an example and comment out .hoverInfo

```
//     .hoverInfo(['Ortsname','PKWDICHT2013'])
.applyBehavior(mapmap.behavior.zoom())
```

So non-thematic maps can't zoom (I know that's not the point of mapmap.js, but still).

**Comment by floledermann** [comment]
Fixed in master, release pending.
