### ISSUE TITLE
Missing value handling

### ISSUE THREAD

**Issue by wahlatlas** [floledermann/mapmap.js#20]
Maybe I am missing something about the D3 `scale` functionality, but it would be very helpful if one could specify missing values in the `meta` declaration (per variable or per loaded .csv file).

Bonus points if the legend would display a color separate from a colorbrewer scale to indicate missing values.

**Comment by floledermann** [comment]
I am at a conference until next Tuesday, please stay tuned until next week...

**Comment by floledermann** [comment]
See #23 - this is now supported through the `undefinedValue` and `undefinedColor` metadata fields. New release coming soon.
