### ISSUE TITLE
Legend for threshold scale is wrong, suggestions for improvement

### ISSUE THREAD

**Issue by wahlatlas** [floledermann/mapmap.js#22]
As per the D3 api 
https://github.com/mbostock/d3/wiki/Quantitative-Scales#threshold-scales
a threshold scale works like this

```
var t = d3.scale.threshold().domain([0, 1]).range(['a', 'b', 'c']); 
t(-1) === 'a';
t(0) === 'b';
t(0.5) === 'b';
t(1) === 'c';
```

However the _mapmap.js_ legend puts a **>** (greater than) on the lower boundary of a class whereas that threshold is already included in that class (the class starts with the threshold value)

Related, see #11 

For a given scale

```
scale: 'threshold',
domain: [450, 550, 650], 
```

the correct legend would be

![threshold](https://cloud.githubusercontent.com/assets/4449821/10268042/69277efc-6aac-11e5-9603-31641ee6c6bb.png)

Obviously this is a little convoluted (German statisticians like to phrase legends in the form of _von 450 bis unter 550_). Instead one could leave the boundary question ambiguous in using a minimalist legend like Mike Bostock once suggested in http://bl.ocks.org/mbostock/5144735

![legend_alternative](https://cloud.githubusercontent.com/assets/4449821/10268105/3866d860-6aae-11e5-9672-527a6cc20642.png)
If users wanted to find out exact values they always have `.hoverInfo`. The above legend has the added benefit of visually depicting the value distribution similar to a box-plot (alas the above image is not to scale, see it in action for various distributions at https://www.destatis.de/zensuskarte).

**Comment by floledermann** [comment]
This should have been fixed by the recent refactoring of legend generation. Built mapmap.js checked in in master, release forthcoming.

I am working on some examples of how to customize legend labeling & layout easily, stay tuned on the [mapmap-examples repo](https://github.com/floledermann/mapmap-examples) (`test/legends.html`) which will hopefully be available online too, soon.
