### ISSUE TITLE
numberformat:'d' prevents display in tooltip for numbers with decimal places

### ISSUE THREAD

**Issue by wahlatlas** [floledermann/mapmap.js#24]
Using `numberFormat:'d'` in the `meta` definition allows only integers to be displayed in the `.hoverInfo`tooltip, whereas numbers with decimal places are not displayed at all, not even their label. This can currently be worked around with `numberFormat:'0f'`

**Comment by floledermann** [comment]
Formatting Strings are passed through to [d3.format](https://github.com/mbostock/d3/wiki/Formatting#numbers), which is implemented this way ("_use Number.toString, but ignore any non-integer values_")

I added a note in the [documentation](https://github.com/floledermann/mapmap.js/wiki/API-Documentation#metadata-fields), though.
