### ISSUE TITLE
legend.html histogram has unrealistic scale for large numbers

### ISSUE THREAD

**Issue by wahlatlas** [floledermann/mapmap.js#29]
Currently the histogram code doesn't seem to take into consideration possible max values, following example from a map with 11k municipalities

![histogr](https://cloud.githubusercontent.com/assets/4449821/11304408/322b4304-8fa8-11e5-9b50-f546dea7e3f7.png)

**Comment by floledermann** [comment]
:) You can set the `histogramBarWidth` option of the legend to a function that accepts a count parameter and returns a pixel value for the width of the bar like so:

``` js
map.legend(mapmap.legend.html({
        histogram: true,
        histogramBarWidth: function(count) {
            return count / 1000;
        }
    }))
```

Using a function means you could also use a D3 scale for this.

I just committed an update in the master branch that also accepts a constant scaling factor in place of a function (i.e. the number of pixels per counted entity), so above can be shortened to:

``` js
map.legend(mapmap.legend.html({
        histogram: true,
        histogramBarWidth: 0.001
    }))
```

An open question is how to do scaling relative to some overall statistics, e.g. the total number of entities or the maximum number in one class. Therefore I had the feeling that this is not completely settled and did not document it yet.

**Comment by wahlatlas** [comment]
Thanks, very helpful!
