### ISSUE TITLE
List of real-world mapmap.js examples

### ISSUE THREAD

**Issue by wahlatlas** [floledermann/mapmap.js#35]
It all started with the genderATlas for Austria
http://genderatlas.at/articles/buergermeisterinnen.html

Then I myself did two maps for state elections in Germany (March 2016):

Baden Württemberg
http://vis.uell.net/bawue/16/atlas.html

Rheinland-Pfalz / Rhineland-Palatinate
http://vis.uell.net/rlp/16/atlas.html

The Federal Statistical Office of Germany published a map on local business taxes for over 11,000 municipalities (April 2016, german only)
https://www.destatis.de/DE/ZahlenFakten/GesellschaftStaat/OeffentlicheFinanzenSteuern/Steuern/Steuerhaushalt/Karte/Hebesaetze.html

to be continued

**Comment by wahlatlas** [comment]
Another map from the Federal Statistical Office of Germany, on the regional impact of minimum wage (minimum wage as percentage of average wage, german only) 258 job market regions
https://www.destatis.de/DE/ZahlenFakten/GesamtwirtschaftUmwelt/VerdiensteArbeitskosten/Mindestloehne/Karte/Mindestloehne.html

**Comment by floledermann** [comment]
Thanks! I added these to the [Wiki Page](https://github.com/floledermann/mapmap.js/wiki/Examples) - if you knwo of any more exmaples, please send to me and I will add them to that page.
