### ISSUE TITLE
TSV support for data input

### ISSUE THREAD

**Issue by kannes** [floledermann/mapmap.js#4]
Please add support for tab-separated input for the "data" in addition to CSV. Tab-separated files are so much more fun :)

**Comment by floledermann** [comment]
Moved to underlying [datadata](https://github.com/floledermann/datadata.js) library into a [somewhat extended issue](https://github.com/floledermann/datadata.js/issues/2). Working on it.

**Comment by floledermann** [comment]
Actually leaving this open until resolved

**Comment by floledermann** [comment]
Fixed in master, release pending :)
