### ISSUE TITLE
How to get different stroke colors?

### ISSUE THREAD

**Issue by irenenirgendwo** [floledermann/mapmap.js#42]
I used the function `.strokeColor('value2')` in combination with .strokeColor('value')` to get a different stroke color for a region which should be marked. In the csv-data I set value2 equal 0 for all other regions and 1 for this special region and defined two colors in the metadata. 

Is there still any possibility to get something like this? I tried with 

``` javascript
.symbolizeAttribute('auswahl')
.meta({
        'value': {
             ...
          },
        'auswahl':{
          label: 'Auswahl',
          stroke: ['#ffffff','#e10019'],
          stroke-width: [1.0,4.0]
        }
      })
```

but it didn't work.

**Comment by floledermann** [comment]
Is this with the older version you were referring to in #41 ? - `symbolizeAttribute` was only added peroperly in 0.2.8, so it doesn't work with oder versions. I will look into the other issue tomorrow...

**Comment by irenenirgendwo** [comment]
Thanks. No, this is what i tried with the new version.

With the older version i got something like this to work as expected:

``` javascript
.strokeColor('auswahl')
.meta({
        'value': {
             ...
          },
        'auswahl':{
          label: 'Auswahl',
          color: ['#ffffff','#e10019']
        }
      })
```

**Comment by floledermann** [comment]
It should be

```
.symbolizeAttribute('auswahl','stroke')
```

see [custom symbolization examples](http://floledermann.github.io/mapmap-examples/tutorial/symbolization.html)

**Comment by irenenirgendwo** [comment]
Thanks, the custom symbolization ist great.
