### ISSUE TITLE
source link not commented out

### ISSUE THREAD

**Issue by wahlatlas** [floledermann/mapmap.js#9]
Lines 22-24 of _mapmap.js_ show this URL not being commented out properly

```
// test whether in a browser environment
http://stackoverflow.com/a/4224668/171579
if (typeof window === 'undefined') {
```

**Comment by floledermann** [comment]
Wow - turns out the reason why this didn't fail tests is that JS interprets a line starting with `http://...` as a label named "http", followed by a comment :open_mouth:

Out of curiosity: did this fail for you, did you lint the code or did you read the code really closely? 

Fixed in master and 0.2.4

**Comment by wahlatlas** [comment]
I just tried to read the code and this was one of the few parts that I could understand.
Most of the problems right now are likely on my side and I am working my way through one step at a time.

My maps still look more like Joan Miro paintings though than a choropleth of Germany (#d3brokeandmadeart) but that is probably more related to my _mapshaper.org_ derived topojson files.

I'd much appreciate if you could post your Austria example so that one could narrow down the problems. E.g. does the localization feature (numberformats) already work?

![d3brokeandmadeart](https://cloud.githubusercontent.com/assets/4449821/8991706/aa84813c-36fa-11e5-84f0-af89dcc5c8a9.png)

**Comment by floledermann** [comment]
I made some fixes to localization code a few days ago, pls make sure you use the most current version (File mapmap.js in GitHub repo root). This file is built with browserify from multiple libs, so if you want to study mapmap.js code (and undocumented API methods ;) ) the file src/index.js would be a better starting point. Basically if you pass `{locale: 'de'}` as a second argument to mapmap(), the built-in German locale should be activated.

Generally feel free to email me with questions (addr is in my GitHub profile), unfortunately I'm leaving **tomorrow** for two weeks of offline-holidays and I didn't even manage to finish the documentation properly... so stay tuned for more to come later in August or September.

Ach ja, und ich nehme an wir können auch deutsch reden ;)

Best, Flo
